# ruff: noqa: F401
# SPDX-License-Identifier: GPL-3.0-or-later

"""Geometry helpers for ydd Symmetric Edit.

The interactive cut is deliberately left to Blender's native tools. This module
marks the pre-cut topology, identifies the edges Blender created, and mirrors
their topology directly on the opposite faces.
"""

from __future__ import annotations

from mathutils import Vector  # noqa: F401
from mathutils.kdtree import KDTree  # noqa: F401

from ._types import (
    CarrierFrameMap,
    CarrierFrameSnapshot,
    Coordinate3D,
    EdgeMarkerId,
    EdgeSelectionHistory,
    FaceId,
    FaceKey,
    FaceSelectionHistory,
    HiddenFaceMap,
    MirrorFaceMap,
    MirrorOverlap,
    OverlapClassification,
    QuantizedCoordinate,
    SelectionHistory,
    SelectionSnapshot,
    TopologyPreparation,
    VertexSelectionHistory,
)  # noqa: F401
from .face_mapping import (
    FaceRegistry,
    _canonical_carrier_frames,
    _face_key,
    _region_allows_orphan_self_map,
    _snapshot_face_map,
    resolve_live_mirror_face_map,
)  # noqa: F401
from .matching import (
    _INJECTIVE_STEP_LIMIT,
    AXIS_INDEX,
    MESH_SYMMETRY_PROPERTIES,
    VertexMirrorLookup,
    VertexRegistry,
    _chebyshev_distance_3d,
    _coordinate_3d,
    _coords_match_chebyshev,
    _injective_tie_margin,
    _iter_quantized_neighborhood,
    _one_sided_candidate_arrays,
    _one_sided_pair_table,
    _quantized_coordinate,
    _solve_injective_component,
    _vertex_pair_table_from_lookup,
    build_vertex_mirror_lookup,
    build_vertex_pair_table,
    classify_selection_overlap,
    coordinates_match,
    enabled_mesh_symmetry_axes,
    mirror_coordinate,
)  # noqa: F401
from .selection import (
    _restore_selection_history,
    _selection_element_coordinate,
    add_selection_layers,
    extend_selection_to_mirror,
    restore_visibility_and_selection,
)  # noqa: F401
from .snapshot import (
    EDGE_HIDDEN_LAYER,
    EDGE_ORIGINAL_LAYER,
    EDGE_SELECTION_LAYER,
    FACE_HIDDEN_LAYER,
    FACE_ID_LAYER,
    FACE_MIRROR_ID_LAYER,
    FACE_SELECTION_LAYER,
    HISTORY_TOKEN_LAYER,
    TEMP_LAYER_NAMES,
    VERT_BACKUP_ID_LAYER,
    VERT_COLLAPSE_GROUP_LAYER,
    VERT_HIDDEN_LAYER,
    VERT_MERGE_GROUP_LAYER,
    VERT_RIP_ID_LAYER,
    VERT_SELECTION_LAYER,
    LazyCarrierFrameMap,
    LazyTopologyResolution,
    _capture_bmesh_snapshot,
    _capture_mesh_snapshot,
    _carrier_frame_from_coords,
    _carrier_frame_snapshot,
    get_required_layers,
    prepare_topology,
    remove_temporary_layers,
    remove_temporary_mesh_attributes,
)  # noqa: F401
from .stitch import (
    _MIN_SIDE_LENGTH,
    _PROJECTION_STEP_LIMIT,
    _assign_projection_candidates,
    _canonical_edge_endpoints,
    _classify_segment_contact,
    _collect_reflected_path_context,
    _coordinate_tuple,
    _cross_2d,
    _deduplicate_occurrences,
    _discover_path_edges,
    _distance_to_line_2d,
    _edge_carrier_ids,
    _edge_coordinate_key,
    _edge_coordinate_key_matches,
    _edge_keys_matching_lookup,
    _edge_side,
    _edge_survivor_key,
    _EdgeEndpointEntry,
    _EdgeEndpointStore,
    _intersect_segments_on_carrier,
    _intersection_results_match,
    _is_interior_edge_factor,
    _is_path_edge_by_markers,
    _lex_first_edge,
    _mapped_projection_edge_set,
    _match_edge_endpoint_pair,
    _match_edge_endpoint_pair_for_faces,
    _matching_endpoint_index,
    _mirror_invariant_endpoint_key,
    _mirrored_carrier_ids,
    _MirroredPathCrossingCluster,
    _MirroredPathOccurrence,
    _MirroredSegmentIntersection,
    _nearby_projection_candidates,
    _occurrence,
    _plan_plane_stitch_vertex,
    _plan_tolerance,
    _point_segment_distance_2d,
    _point_segment_distance_and_factor,
    _project_to_carrier,
    _RawMirroredPathCrossing,
    _register_edge_endpoint_pair,
    _resolve_reflected_vertex_on_target,
    _target_faces_by_id,
    apply_collapsed_offset_topology,
    apply_crosses_p_stitch,
    apply_mirrored_path_crossings,
    apply_reflected_loop_topology,
    apply_reflected_path_topology,
    build_reflected_cutter,
    choose_source_side,
    classify_path_edges_by_side,
    cluster_points_by_tolerance,
    collapsed_offset_target_edge_markers,
    collect_knife_path_edges_by_side,
    collect_source_path_edges,
    is_self_mirrored_edge,
    native_path_edge_state,
    path_ring_includes_pre_hidden_edges,
    plan_mirrored_path_crossings,
    plane_intersection_of_edge,
    reflected_path_uses_only_target_boundaries,
    reserve_source_path_marker,
    snap_projected_graph,
    target_face_ids_for_edges,
)  # noqa: F401
